const express = require('express')
const cors = require('cors')
const mongoose =require('mongoose')
require('dotenv').config()
const app = express()
const userRouter=require('./route/user.route')
const adminRouter = require('./route/admin.route')
app.use(express.json())
mongoose.connect(process.env.DATABASE_URL).then(console.log('connected'))
app.use(cors())

app.use('/api',userRouter,adminRouter)
app.listen(3001 , ()=>console.log("server on"))
