import Dashboard from "@/component/admin/admindash/Admindash"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body><Dashboard/>{children}</body>
    </html>
  )
}
